const mongoose = require('mongoose');

const newsSchema = new mongoose.Schema({
    heading: {
        type: String,
        required: true,
        trim: true
    },
    content: {
        type: String,
        required: true
    },
    full: {
        type: Boolean,
        default: false
    },
    category: {
        type: String,
        required: true,
        enum: ['desh', 'videsh', 'rajya', 'bhopal', 'crime', 'khel', 'rajniti', 'manoranjan', 'vyapar', 'itihas']
    },
    author: {
        type: String,
        required: true,
        trim: true
    },
    photos: {
        type: [String],
        default: []
    },
    date: {
        type: Date,
        default: Date.now
    },
    views: {
        type: Number,
        default: 0
    },
    formattedDate: {
        type: String
    },
    rssLink: {
        type: String,
        default: null
    },
    rssSource: {
        type: String,
        default: null
    },
    headingNorm: {
        type: String,
        default: null
    },
    isPermanent: {
        type: Boolean,
        default: false
    },
    isOriginal: {
        type: Boolean,
        default: false
    },
    isAajKaItihas: {
        type: Boolean,
        default: false
    },
    // True only for articles published via the admin's AI-scraper tool — used to
    // hide the separate "पूरी खबर पढ़ें" button since the clickable source-credit
    // link already covers that for these (unlike plain RSS/API imports).
    isAiScraped: {
        type: Boolean,
        default: false
    },
    isDailyFact: {
        type: Boolean,
        default: false
    },
    slug: {
        type: String,
        default: null
    },
    // 60-second short format generated by Groq
    shortNews: {
        headline:   { type: String, default: null },
        whatHappened: { type: String, default: null },
        keyPoints:  { type: [String], default: [] },
        whyItMatters: { type: String, default: null },
        generatedAt:  { type: Date, default: null }
    },
    // Background context / explainer generated by Groq (90-120 word पृष्ठभूमि section)
    explainer: {
        text:        { type: String, default: null },
        generatedAt: { type: Date, default: null }
    },
    // Editorial moral lesson for crime articles — "वॉयस ऑफ क्रांति का मत"
    kaMat: {
        text:        { type: String, default: null },
        generatedAt: { type: Date, default: null }
    }
}, {
    timestamps: true
});

// ── Indexes for fast queries ──────────────────────────────────────────────────
// Homepage / all-news feed: sort by date
newsSchema.index({ date: -1 });
// Category feed: filter by category, sort by date (most used query)
newsSchema.index({ category: 1, date: -1 });
// Author filter + date sort
newsSchema.index({ author: 1, date: -1 });
// Shorts generation: find unprocessed articles per category
newsSchema.index({ category: 1, 'shortNews.generatedAt': 1, date: -1 });
// RSS duplicate check by link
newsSchema.index({ rssLink: 1 }, { sparse: true });
// Slug lookup (article detail page) — sparse because older docs may have null slug
newsSchema.index({ slug: 1 }, { unique: true, sparse: true });
// ─────────────────────────────────────────────────────────────────────────────

// ── Devanagari → Roman transliteration (slug-quality rewrite) ────────────────
// Each consonant carries its inherent 'a' vowel. That 'a' is stripped when
// a vowel matra (diacritic) or a halant (virama ् ) follows it.
const CONSONANT_MAP = {
    'क':'ka',  'ख':'kha', 'ग':'ga',  'घ':'gha', 'ङ':'nga',
    'च':'cha', 'छ':'chha','ज':'ja',  'झ':'jha', 'ञ':'nya',
    'ट':'ta',  'ठ':'tha', 'ड':'da',  'ढ':'dha', 'ण':'na',
    'त':'ta',  'थ':'tha', 'द':'da',  'ध':'dha', 'न':'na',
    'प':'pa',  'फ':'fa',  'ब':'ba',  'भ':'bha', 'म':'ma',
    'य':'ya',  'र':'ra',  'ल':'la',  'व':'va',  'ळ':'la',
    'श':'sha', 'ष':'sha', 'स':'sa',  'ह':'ha',
};
const MATRA_MAP   = { 'ा':'a','ि':'i','ी':'i','ु':'u','ू':'u','े':'e','ै':'ai','ो':'o','ौ':'au','ृ':'ri' };
const VOWEL_MAP   = { 'अ':'a','आ':'aa','इ':'i','ई':'i','उ':'u','ऊ':'u','ए':'e','ऐ':'ai','ओ':'o','औ':'au','ऋ':'ri','ॠ':'ri' };
const DIGIT_MAP   = { '०':'0','१':'1','२':'2','३':'3','४':'4','५':'5','६':'6','७':'7','८':'8','९':'9' };
const HALANT      = '्';

function transliterate(text) {
    let result = '';
    const chars = [...text];
    for (let i = 0; i < chars.length; i++) {
        const ch   = chars[i];
        const next = chars[i + 1];
        // Anusvara / chandrabindu → 'n' (nasalization — was being silently dropped)
        if (ch === 'ं' || ch === 'ँ') {
            result += 'n';
        } else if (ch === 'ः' || ch === '़' || ch === '।' || ch === '॥') {
            // Visarga, nukta, dandas → skip
        } else if (CONSONANT_MAP[ch]) {
            if (next === HALANT) {
                // Halant cancels inherent 'a' → emit consonant-only, skip halant
                result += CONSONANT_MAP[ch].slice(0, -1);
                i++;
            } else if (MATRA_MAP[next] !== undefined) {
                // Matra follows → strip inherent 'a' (matra supplies the vowel)
                result += CONSONANT_MAP[ch].slice(0, -1);
            } else if (!next || /[\s\u2013\u2014\-_,!?:;।॥""''()]/.test(next)) {
                // Word-final consonant: Hindi schwa deletion (final inherent 'a' is silent)
                // e.g. 'भारत' → 'bharat' not 'bharata', 'बैठक' → 'baithak' not 'baithaka'
                result += CONSONANT_MAP[ch].slice(0, -1);
            } else {
                result += CONSONANT_MAP[ch];
            }
        } else if (MATRA_MAP[ch] !== undefined) {
            result += MATRA_MAP[ch];
        } else if (VOWEL_MAP[ch]) {
            result += VOWEL_MAP[ch];
        } else if (DIGIT_MAP[ch]) {
            result += DIGIT_MAP[ch];
        } else if (/[a-zA-Z0-9]/.test(ch)) {
            result += ch.toLowerCase();
        } else if (/[\s\u2013\u2014\-_,!?:;।॥""''()]/.test(ch)) {
            // Separators including em-dash, en-dash, smart quotes → word boundary
            result += '-';
        }
        // All other unmapped chars silently dropped — slug stays pure ASCII
    }
    return result;
}

// Common Hindi stop words — omitted from URL slugs to keep them clean & short
const SLUG_STOP_WORDS = new Set([
    'में','भी','गए','ने','से','पर','और','यह','वह','एक','दो','कि','को','का','के','की',
    'है','हैं','था','थी','थे','हो','हुए','हुई','हुआ','जो','तो','लेकर','बाद','पहले',
    'अब','तक','साथ','द्वारा','मैं','हम','आप','वे','जब','तब','ये','वो','इस','उस',
    'इन','उन','आज','कल','फिर','मगर','जिस','जिन','दे','दिए','दिया','कर','करके',
    'नहीं','ही','तथा','एवं','व','इसलिए','इसके','उसके','उनके','आदि','जैसे','होगा',
    'होगी','होंगे','किया','किए','किसी','किसने','कहा','बोला','चाहिए','बहुत',
]);

function generateSlug(heading) {
    // 1. Split into words; filter stop words; take first 6 significant words
    const words = heading.split(/[\s,।\-:!?;]+/).filter(w => w.length >= 2);
    const significant = words.filter(w => !SLUG_STOP_WORDS.has(w)).slice(0, 6);
    const toSlugify = significant.length >= 2 ? significant : words.slice(0, 6);
    // 2. Transliterate, collapse hyphens, trim, cap at 50 chars
    const base = transliterate(toSlugify.join(' '))
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 50);
    return base || transliterate(heading).replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 50);
}
// ─────────────────────────────────────────────────────────────────────────────

// Create formatted date and slug before saving (async to allow uniqueness check)
newsSchema.pre('save', async function() {
    if (!this.formattedDate) {
        this.formattedDate = new Date(this.date).toLocaleDateString('hi-IN', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
        });
    }
    if (!this.slug && this.heading) {
        const base = generateSlug(this.heading);
        let slug = base;
        let counter = 1;
        // Ensure uniqueness — append -2, -3 … only on collision
        while (await this.constructor.findOne({ slug, _id: { $ne: this._id } }).select('_id').lean()) {
            counter++;
            slug = `${base}-${counter}`;
        }
        this.slug = slug;
    }
});

module.exports = { News: mongoose.model('News', newsSchema), generateSlug, transliterate };
